---
title: "16S_EC_ml_importances"
author: "Heather Deel"
date: "2023-11-08"
output: html_document
---

### Compiling variable importances for all EC models for all indicators

### Libraries
```{r}
library(tidyverse)
```

### Import importances for all indicators
# ACE
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_EC/ACE_model_results_clay_climate",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-1]

# format column names
colnames <- c("EC_number","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
ace_shared <- ldf %>% reduce(inner_join, by = "EC_number")

# calculate average importance of all shared features
ace_shared$avg_imp <- rowMeans(ace_shared[,2:26])
ace_shared <- ace_shared[,c(1,27)]
ace_shared <- data.frame(ace_shared)
colnames(ace_shared)[1] <- "feature"
ace_shared$indicator <- "ACE"

# add Gibbs info to important features
enzyme_list <- read.csv("ec_files_expasy/enzyme.csv")
enzyme_list$feature <- paste("EC_",enzyme_list$EC_number, sep = "")
enzyme_list$feature <- gsub("\\.","_", enzyme_list$feature)
enzyme_list <- enzyme_list[,2:3]
ace_info <- ace_shared %>% 
  left_join(enzyme_list, by = "feature")

# get NAs in EC_name to be clay and climate
ace_info[72,4] <- "clay"
ace_info[73,4] <- "climate"

# ID features in our soil gibbs list
enzyme_gibbs <- read.csv("picrust2_files/GIBBs.EC.numbers.csv")
colnames(enzyme_gibbs)[1] <- "feature"
enzyme_gibbs$feature <- gsub("\\.","_", enzyme_gibbs$feature)
ace_info <- ace_info %>% 
  left_join(enzyme_gibbs, by = "feature")
ace_info$Category <- ace_info$Category %>% 
  replace_na("Unknown")

# graph all important features with gibbs features highlighted
p1 <- ggplot(ace_info, aes(x = reorder(EC_name, -avg_imp), y = avg_imp, fill = Category)) +
  geom_bar(stat = "identity", width = .5) +
  scale_fill_manual(values = c("#00AC10","#FF0000","#B5B5B5")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "ACE Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_EC_ACE.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_EC_ACE.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")

```

# ACTIVE C
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_EC/ACTIVEC_model_results_clay_climate",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-1]

# format column names
colnames <- c("EC_number","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
activeC_shared <- ldf %>% reduce(inner_join, by = "EC_number")

# calculate average importance of all shared features
activeC_shared$avg_imp <- rowMeans(activeC_shared[,2:26])
activeC_shared <- activeC_shared[,c(1,27)]
activeC_shared <- data.frame(activeC_shared)
colnames(activeC_shared)[1] <- "feature"
activeC_shared$indicator <- "ACTIVEC"

# add Gibbs info to important features
activeC_info <- activeC_shared %>% 
  left_join(enzyme_list, by = "feature")

# get NAs in EC_name to be the correct
activeC_info[50,4] <- "climate"

# ID features in our soil gibbs list
activeC_info <- activeC_info %>% 
  left_join(enzyme_gibbs, by = "feature")
activeC_info$Category <- activeC_info$Category %>% 
  replace_na("Unknown")

# graph all important features with gibbs features highlighted
# there are no gibbs features in this one
p1 <- ggplot(activeC_info, aes(x = reorder(EC_name, -avg_imp), y = avg_imp, fill = Category)) +
  geom_bar(stat = "identity", width = .5) +
  scale_fill_manual(values = c("#B5B5B5")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Active C Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_EC_ACTIVEC.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_EC_ACTIVEC.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

# Aggregate Stability
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_EC/AGGSTAB_model_results_clay_climate",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-1]

# format column names
colnames <- c("EC_number","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
aggstab_shared <- ldf %>% reduce(inner_join, by = "EC_number")

# calculate average importance of all shared features
aggstab_shared$avg_imp <- rowMeans(aggstab_shared[,2:26])
aggstab_shared <- aggstab_shared[,c(1,27)]
aggstab_shared <- data.frame(aggstab_shared)
colnames(aggstab_shared)[1] <- "feature"
aggstab_shared$indicator <- "AGGSTAB"

# add Gibbs info to important features
aggstab_info <- aggstab_shared %>% 
  left_join(enzyme_list, by = "feature")

# get NAs in EC_name to be clay and climate
aggstab_info[54,4] <- "climate"

# ID features in our soil gibbs list
enzyme_gibbs <- read.csv("picrust2_files/GIBBs.EC.numbers.csv")
colnames(enzyme_gibbs)[1] <- "feature"
enzyme_gibbs$feature <- gsub("\\.","_", enzyme_gibbs$feature)
aggstab_info <- aggstab_info %>% 
  left_join(enzyme_gibbs, by = "feature")
aggstab_info$Category <- aggstab_info$Category %>% 
  replace_na("Unknown")

# graph all important features with gibbs features highlighted
p1 <- ggplot(aggstab_info, aes(x = reorder(EC_name, -avg_imp), y = avg_imp, fill = Category)) +
  geom_bar(stat = "identity", width = .5) +
  scale_fill_manual(values = c("#FF0000","#B5B5B5")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Aggregate Stability Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_EC_AGGSTAB.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_EC_AGGSTAB.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

# CASH
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_EC/CASH_model_results_clay_climate",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-26]

# format column names
colnames <- c("EC_number","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
cash_shared <- ldf %>% reduce(inner_join, by = "EC_number")

# calculate average importance of all shared features
cash_shared$avg_imp <- rowMeans(cash_shared[,2:26])
cash_shared <- cash_shared[,c(1,27)]
cash_shared <- data.frame(cash_shared)
colnames(cash_shared)[1] <- "feature"
cash_shared$indicator <- "CASH"

# add Gibbs info to important features
cash_info <- cash_shared %>% 
  left_join(enzyme_list, by = "feature")

# get NAs in EC_name to be the correct
cash_info[19,4] <- "clay"
cash_info[20,4] <- "climate"

# ID features in our soil gibbs list
cash_info <- cash_info %>% 
  left_join(enzyme_gibbs, by = "feature")
cash_info$Category <- cash_info$Category %>% 
  replace_na("Unknown")

# graph all important features with gibbs features highlighted
p1 <- ggplot(cash_info, aes(x = reorder(EC_name, -avg_imp), y = avg_imp, fill = Category)) +
  geom_bar(stat = "identity", width = .5) +
  scale_fill_manual(values = c("#B5B5B5")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "CASH Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_EC_CASH.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_EC_CASH.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

# Disturbance
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_EC/DIST_model_results_clay_climate",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-1]

# format column names
colnames <- c("EC_number","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
dist_shared <- ldf %>% reduce(inner_join, by = "EC_number")

# calculate average importance of all shared features
dist_shared$avg_imp <- rowMeans(dist_shared[,2:26])
dist_shared <- dist_shared[,c(1,27)]
dist_shared <- data.frame(dist_shared)
colnames(dist_shared)[1] <- "feature"
dist_shared$indicator <- "DIST"

# add Gibbs info to important features
dist_info <- dist_shared %>% 
  left_join(enzyme_list, by = "feature")

# get NAs in EC_name to be the correct
dist_info[94,4] <- "climate"

# ID features in our soil gibbs list
dist_info <- dist_info %>% 
  left_join(enzyme_gibbs, by = "feature")
dist_info$Category <- dist_info$Category %>% 
  replace_na("Unknown")

# graph all important features with gibbs features highlighted
p1 <- ggplot(dist_info, aes(x = reorder(EC_name, -avg_imp), y = avg_imp, fill = Category)) +
  geom_bar(stat = "identity", width = .5) +
  scale_fill_manual(values = c("#B5B5B5")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Disturbance Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_EC_DIST.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_EC_DIST.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

# Respiration
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_EC/RESP_model_results_clay_climate",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-1]

# format column names
colnames <- c("EC_number","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
resp_shared <- ldf %>% reduce(inner_join, by = "EC_number")

# calculate average importance of all shared features
resp_shared$avg_imp <- rowMeans(resp_shared[,2:26])
resp_shared <- resp_shared[,c(1,27)]
resp_shared <- data.frame(resp_shared)
colnames(resp_shared)[1] <- "feature"
resp_shared$indicator <- "RESP"

# add Gibbs info to important features
resp_info <- resp_shared %>% 
  left_join(enzyme_list, by = "feature")

# get NAs in EC_name to be the correct
resp_info[54,4] <- "climate"

# ID features in our soil gibbs list
resp_info <- resp_info %>% 
  left_join(enzyme_gibbs, by = "feature")
resp_info$Category <- resp_info$Category %>% 
  replace_na("Unknown")

# graph all important features with gibbs features highlighted
p1 <- ggplot(resp_info, aes(x = reorder(EC_name, -avg_imp), y = avg_imp, fill = Category)) +
  geom_bar(stat = "identity", width = .5) +
  scale_fill_manual(values = c("#FF0000","#B5B5B5")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Respiration Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_EC_RESP.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_EC_RESP.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

# Richness
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_EC/RICH_model_results_clay_climate",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-1]

# format column names
colnames <- c("EC_number","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
rich_shared <- ldf %>% reduce(inner_join, by = "EC_number")

# calculate average importance of all shared features
rich_shared$avg_imp <- rowMeans(rich_shared[,2:26])
rich_shared <- rich_shared[,c(1,27)]
rich_shared <- data.frame(rich_shared)
colnames(rich_shared)[1] <- "feature"
rich_shared$indicator <- "RICH"

# add Gibbs info to important features
rich_info <- rich_shared %>% 
  left_join(enzyme_list, by = "feature")

# get NAs in EC_name to be the correct
rich_info[37,4] <- "climate"

# ID features in our soil gibbs list
rich_info <- rich_info %>% 
  left_join(enzyme_gibbs, by = "feature")
rich_info$Category <- rich_info$Category %>% 
  replace_na("Unknown")

# graph all important features with gibbs features highlighted
p1 <- ggplot(rich_info, aes(x = reorder(EC_name, -avg_imp), y = avg_imp, fill = Category)) +
  geom_bar(stat = "identity", width = .5) +
  scale_fill_manual(values = c("#FF0000","#B5B5B5")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Richness Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_EC_RICH.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_EC_RICH.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

# Roots
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_EC/ROOT_model_results_clay_climate",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-1]

# format column names
colnames <- c("EC_number","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
root_shared <- ldf %>% reduce(inner_join, by = "EC_number")

# calculate average importance of all shared features
root_shared$avg_imp <- rowMeans(root_shared[,2:26])
root_shared <- root_shared[,c(1,27)]
root_shared <- data.frame(root_shared)
colnames(root_shared)[1] <- "feature"
root_shared$indicator <- "ROOT"

# add Gibbs info to important features
root_info <- root_shared %>% 
  left_join(enzyme_list, by = "feature")

# get NAs in EC_name to be the correct
root_info[21,4] <- "climate"

# ID features in our soil gibbs list
root_info <- root_info %>% 
  left_join(enzyme_gibbs, by = "feature")
root_info$Category <- root_info$Category %>% 
  replace_na("Unknown")

# graph all important features with gibbs features highlighted
p1 <- ggplot(root_info, aes(x = reorder(EC_name, -avg_imp), y = avg_imp, fill = Category)) +
  geom_bar(stat = "identity", width = .5) +
  scale_fill_manual(values = c("#00AC10","#B5B5B5")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Root Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_EC_ROOT.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_EC_ROOT.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

# SEMWISE
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_EC/SEMWISE_model_results_clay_climate",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-26]

# format column names
colnames <- c("EC_number","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
semwise_shared <- ldf %>% reduce(inner_join, by = "EC_number")

# calculate average importance of all shared features
semwise_shared$avg_imp <- rowMeans(semwise_shared[,2:26])
semwise_shared <- semwise_shared[,c(1,27)]
semwise_shared <- data.frame(semwise_shared)
colnames(semwise_shared)[1] <- "feature"
semwise_shared$indicator <- "SEMWISE"

# add Gibbs info to important features
semwise_info <- semwise_shared %>% 
  left_join(enzyme_list, by = "feature")

# get NAs in EC_name to be the correct
semwise_info[27,4] <- "climate"

# ID features in our soil gibbs list
semwise_info <- semwise_info %>% 
  left_join(enzyme_gibbs, by = "feature")
semwise_info$Category <- semwise_info$Category %>% 
  replace_na("Unknown")

# graph all important features with gibbs features highlighted
p1 <- ggplot(semwise_info, aes(x = reorder(EC_name, -avg_imp), y = avg_imp, fill = Category)) +
  geom_bar(stat = "identity", width = .5) +
  scale_fill_manual(values = c("#B5B5B5")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "SEMWISE Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_EC_SEMWISE.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_EC_SEMWISE.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

# SHMI
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_EC/SHMI_model_results_clay_climate",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-26]

# format column names
colnames <- c("EC_number","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
shmi_shared <- ldf %>% reduce(inner_join, by = "EC_number")

# calculate average importance of all shared features
shmi_shared$avg_imp <- rowMeans(shmi_shared[,2:26])
shmi_shared <- shmi_shared[,c(1,27)]
shmi_shared <- data.frame(shmi_shared)
colnames(shmi_shared)[1] <- "feature"
shmi_shared$indicator <- "SHMI"

# add Gibbs info to important features
shmi_info <- shmi_shared %>% 
  left_join(enzyme_list, by = "feature")

# get NAs in EC_name to be the correct
shmi_info[67,4] <- "climate"

# ID features in our soil gibbs list
shmi_info <- shmi_info %>% 
  left_join(enzyme_gibbs, by = "feature")
shmi_info$Category <- shmi_info$Category %>% 
  replace_na("Unknown")

# graph all important features with gibbs features highlighted
p1 <- ggplot(shmi_info, aes(x = reorder(EC_name, -avg_imp), y = avg_imp, fill = Category)) +
  geom_bar(stat = "identity", width = .5) +
  scale_fill_manual(values = c("#0027FF","#00AC10","#FF0000","#B5B5B5")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "SHMI Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_EC_SHMI.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_EC_SHMI.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

# SOM
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_EC/SOM_model_results_clay_climate",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-1]

# format column names
colnames <- c("EC_number","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
som_shared <- ldf %>% reduce(inner_join, by = "EC_number")

# calculate average importance of all shared features
som_shared$avg_imp <- rowMeans(som_shared[,2:26])
som_shared <- som_shared[,c(1,27)]
som_shared <- data.frame(som_shared)
colnames(som_shared)[1] <- "feature"
som_shared$indicator <- "SOM"

# add Gibbs info to important features
som_info <- som_shared %>% 
  left_join(enzyme_list, by = "feature")

# get NAs in EC_name to be the correct
som_info[68,4] <- "clay"
som_info[69,4] <- "climate"

# ID features in our soil gibbs list
som_info <- som_info %>% 
  left_join(enzyme_gibbs, by = "feature")
som_info$Category <- som_info$Category %>% 
  replace_na("Unknown")

# graph all important features with gibbs features highlighted
p1 <- ggplot(som_info, aes(x = reorder(EC_name, -avg_imp), y = avg_imp, fill = Category)) +
  geom_bar(stat = "identity", width = .5) +
  scale_fill_manual(values = c("#00AC10","#B5B5B5")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "SOM Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_EC_SOM.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_EC_SOM.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

# Water capacity
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_EC/WATERCAP_model_results_clay_climate",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-1]

# format column names
colnames <- c("EC_number","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
watercap_shared <- ldf %>% reduce(inner_join, by = "EC_number")

# calculate average importance of all shared features
watercap_shared$avg_imp <- rowMeans(watercap_shared[,2:26])
watercap_shared <- watercap_shared[,c(1,27)]
watercap_shared <- data.frame(watercap_shared)
colnames(watercap_shared)[1] <- "feature"
watercap_shared$indicator <- "WATERCAP"

# add Gibbs info to important features
watercap_info <- watercap_shared %>% 
  left_join(enzyme_list, by = "feature")

# get NAs in EC_name to be the correct
watercap_info[27,4] <- "clay"
watercap_info[28,4] <- "climate"

# ID features in our soil gibbs list
watercap_info <- watercap_info %>% 
  left_join(enzyme_gibbs, by = "feature")
watercap_info$Category <- watercap_info$Category %>% 
  replace_na("Unknown")

# graph all important features with gibbs features highlighted
p1 <- ggplot(watercap_info, aes(x = reorder(EC_name, -avg_imp), y = avg_imp, fill = Category)) +
  geom_bar(stat = "identity", width = .5) +
  scale_fill_manual(values = c("#B5B5B5")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Water Capacity Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_EC_WATERCAP.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_EC_WATERCAP.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

### Combine shared features for all indicators
```{r}
list_EC_dfs <- list(ace_shared, activeC_shared, aggstab_shared, cash_shared,
                    dist_shared,resp_shared, rich_shared, root_shared, 
                    semwise_shared, shmi_shared, som_shared, watercap_shared)
ECs_shared <- list_EC_dfs %>% reduce(inner_join, by = "feature")

# there are no features shared by all 25 models for all indicators
# do a full join and count the number of indicators each feature is important in

ECs_all <- list_EC_dfs %>% reduce(full_join, by = "feature")
ECs_all <- ECs_all[,c(1,3,5,7,9,11,13,15,17,19,21,23,25)]
colnames_list <- c("feature","ACE","ACTIVEC","AGGSTAB","CASH","DIST","RESP",
                   "RICH","ROOT","SEMWISE","SHMI","SOM","WATERCAP")
colnames(ECs_all) <- colnames_list
ECs_all$num_indic_imp <- rowSums(!is.na(ECs_all[,2:13]))

# add info to list of ECs
ECs_all_info <- ECs_all %>% 
  left_join(enzyme_list, by = "feature")

# ID features in our soil gibbs list
ECs_all_info <- ECs_all_info %>% 
  left_join(enzyme_gibbs, by = "feature")
ECs_all_info$Category <- ECs_all_info$Category %>% 
  replace_na("Unknown")

# filter ECs_all down to features that were important in 4 or more indicators
ECs_all_info_filt <- filter(ECs_all_info, num_indic_imp > 3)

# get Nas in EC_name to be correct
ECs_all_info_filt[18,15] <- "clay"
ECs_all_info_filt[19,15] <- "climate"

p1 <- ggplot(ECs_all_info_filt, aes(x = reorder(EC_name, -num_indic_imp), y = num_indic_imp, fill = Category)) +
  geom_bar(stat = "identity", width = .5) +
  scale_fill_manual(values = c("#00AC10","#FF0000","#B5B5B5")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Features Important in Four or More Indicators",
       y = "Number of Indicators Feature is Important In")
p1
ggsave("figures/feat_importance_EC_all.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_EC_all.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```




