---
title: "16S TAX ml importances"
author: "Heather Deel"
date: "2023-11-21"
output: html_document
---

### Compiling variable importances for all taxonomic models for all indicators

### Libraries
```{r}
library(tidyverse)
```

### Import importances for all indicators
# ACE
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_TAX/ACE_model_results",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-1]

# format column names
colnames <- c("Taxon","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
ace_shared <- ldf %>% reduce(inner_join, by = "Taxon")

# calculate average importance of all shared features
ace_shared$avg_imp <- rowMeans(ace_shared[,2:26])
ace_shared <- ace_shared[,c(1,27)]
ace_shared <- data.frame(ace_shared)
ace_shared$indicator <- "ACE"

# there are too many important features to graph
# sort by avg_imp and filter down to the top 50
ace_shared <- ace_shared[order(ace_shared$avg_imp, decreasing = TRUE),] 
ace_shared_t50 <- ace_shared[c(1:50),]

# graph all important features with gibbs features highlighted
p1 <- ggplot(ace_shared_t50, aes(x = reorder(Taxon, -avg_imp), y = avg_imp)) +
  geom_bar(stat = "identity", width = .5) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "ACE Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_TAX_ACE.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_TAX_ACE.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

# Active C
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_TAX/ACTIVEC_model_results",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-1]

# format column names
colnames <- c("Taxon","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
activeC_shared <- ldf %>% reduce(inner_join, by = "Taxon")

# calculate average importance of all shared features
activeC_shared$avg_imp <- rowMeans(activeC_shared[,2:26])
activeC_shared <- activeC_shared[,c(1,27)]
activeC_shared <- data.frame(activeC_shared)
activeC_shared$indicator <- "ACTIVEC"

# there are too many important features to graph
# sort by avg_imp and filter down to the top 50
activeC_shared <- activeC_shared[order(activeC_shared$avg_imp, decreasing = TRUE),] 
activeC_shared_t50 <- activeC_shared[c(1:50),]

# graph all important features with gibbs features highlighted
p1 <- ggplot(activeC_shared_t50, aes(x = reorder(Taxon, -avg_imp), y = avg_imp)) +
  geom_bar(stat = "identity", width = .5) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Active C Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_TAX_ACTIVEC.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_TAX_ACTIVEC.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

# Aggregate Stability
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_TAX/AGGSTAB_model_results",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-1]

# format column names
colnames <- c("Taxon","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
aggstab_shared <- ldf %>% reduce(inner_join, by = "Taxon")

# calculate average importance of all shared features
aggstab_shared$avg_imp <- rowMeans(aggstab_shared[,2:26])
aggstab_shared <- aggstab_shared[,c(1,27)]
aggstab_shared <- data.frame(aggstab_shared)
aggstab_shared$indicator <- "AGGSTAB"

# there are too many important features to graph
# sort by avg_imp and filter down to the top 50
aggstab_shared <- aggstab_shared[order(aggstab_shared$avg_imp, decreasing = TRUE),] 
aggstab_shared_t50 <- aggstab_shared[c(1:50),]

# graph all important features with gibbs features highlighted
p1 <- ggplot(aggstab_shared_t50, aes(x = reorder(Taxon, -avg_imp), y = avg_imp)) +
  geom_bar(stat = "identity", width = .5) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Aggregate Stability Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_TAX_AGGSTAB.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_TAX_AGGSTAB.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

# CASH
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_TAX/CASH_model_results",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-26]

# format column names
colnames <- c("Taxon","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
cash_shared <- ldf %>% reduce(inner_join, by = "Taxon")

# calculate average importance of all shared features
cash_shared$avg_imp <- rowMeans(cash_shared[,2:26])
cash_shared <- cash_shared[,c(1,27)]
cash_shared <- data.frame(cash_shared)
cash_shared$indicator <- "CASH"

# there are too many important features to graph
# sort by avg_imp and filter down to the top 50
cash_shared <- cash_shared[order(cash_shared$avg_imp, decreasing = TRUE),] 
cash_shared_t50 <- cash_shared[c(1:50),]

# graph all important features with gibbs features highlighted
p1 <- ggplot(cash_shared_t50, aes(x = reorder(Taxon, -avg_imp), y = avg_imp)) +
  geom_bar(stat = "identity", width = .5) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "CASH Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_TAX_CASH.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_TAX_CASH.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

# Disturbance
```{r}
# not done on scinet yet
```

# Respiration
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_TAX/RESP_model_results",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-1]

# format column names
colnames <- c("Taxon","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
resp_shared <- ldf %>% reduce(inner_join, by = "Taxon")

# calculate average importance of all shared features
resp_shared$avg_imp <- rowMeans(resp_shared[,2:26])
resp_shared <- resp_shared[,c(1,27)]
resp_shared <- data.frame(resp_shared)
resp_shared$indicator <- "RESP"

# there are too many important features to graph
# sort by avg_imp and filter down to the top 50
resp_shared <- resp_shared[order(resp_shared$avg_imp, decreasing = TRUE),] 
resp_shared_t50 <- resp_shared[c(1:50),]

# graph all important features with gibbs features highlighted
p1 <- ggplot(resp_shared_t50, aes(x = reorder(Taxon, -avg_imp), y = avg_imp)) +
  geom_bar(stat = "identity", width = .5) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Respiration Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_TAX_RESP.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_TAX_RESP.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

# Richness
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_TAX/RICH_model_results",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-1]

# format column names
colnames <- c("Taxon","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
rich_shared <- ldf %>% reduce(inner_join, by = "Taxon")

# calculate average importance of all shared features
rich_shared$avg_imp <- rowMeans(rich_shared[,2:26])
rich_shared <- rich_shared[,c(1,27)]
rich_shared <- data.frame(rich_shared)
rich_shared$indicator <- "RICH"

# there are too many important features to graph
# sort by avg_imp and filter down to the top 50
rich_shared <- rich_shared[order(rich_shared$avg_imp, decreasing = TRUE),] 
rich_shared_t50 <- rich_shared[c(1:50),]

# graph all important features with gibbs features highlighted
p1 <- ggplot(rich_shared_t50, aes(x = reorder(Taxon, -avg_imp), y = avg_imp)) +
  geom_bar(stat = "identity", width = .5) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Richness Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_TAX_RICH.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_TAX_RICH.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

# Roots
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_TAX/ROOT_model_results",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-1]

# format column names
colnames <- c("Taxon","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
root_shared <- ldf %>% reduce(inner_join, by = "Taxon")

# calculate average importance of all shared features
root_shared$avg_imp <- rowMeans(root_shared[,2:26])
root_shared <- root_shared[,c(1,27)]
root_shared <- data.frame(root_shared)
root_shared$indicator <- "ROOT"

# there are too many important features to graph
# sort by avg_imp and filter down to the top 50
root_shared <- root_shared[order(root_shared$avg_imp, decreasing = TRUE),] 
root_shared_t50 <- root_shared[c(1:50),]

# graph all important features with gibbs features highlighted
p1 <- ggplot(root_shared_t50, aes(x = reorder(Taxon, -avg_imp), y = avg_imp)) +
  geom_bar(stat = "identity", width = .5) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Root Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_TAX_ROOT.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_TAX_ROOT.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

# SEMWISE
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_TAX/SEMWISE_model_results",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-26]

# format column names
colnames <- c("Taxon","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
semwise_shared <- ldf %>% reduce(inner_join, by = "Taxon")

# calculate average importance of all shared features
semwise_shared$avg_imp <- rowMeans(semwise_shared[,2:26])
semwise_shared <- semwise_shared[,c(1,27)]
semwise_shared <- data.frame(semwise_shared)
semwise_shared$indicator <- "SEMWISE"

# there are too many important features to graph
# sort by avg_imp and filter down to the top 50
semwise_shared <- semwise_shared[order(semwise_shared$avg_imp, decreasing = TRUE),] 
semwise_shared_t50 <- semwise_shared[c(1:50),]

# graph all important features with gibbs features highlighted
p1 <- ggplot(semwise_shared_t50, aes(x = reorder(Taxon, -avg_imp), y = avg_imp)) +
  geom_bar(stat = "identity", width = .5) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "SEMWISE Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_TAX_SEMWISE.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_TAX_SEMWISE.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

# SHMI
```{r}
# not done on scinet yet
```

# SOM
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_TAX/SOM_model_results",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-1]

# format column names
colnames <- c("Taxon","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
som_shared <- ldf %>% reduce(inner_join, by = "Taxon")

# calculate average importance of all shared features
som_shared$avg_imp <- rowMeans(som_shared[,2:26])
som_shared <- som_shared[,c(1,27)]
som_shared <- data.frame(som_shared)
som_shared$indicator <- "SOM"

# there are too many important features to graph
# sort by avg_imp and filter down to the top 50
som_shared <- som_shared[order(som_shared$avg_imp, decreasing = TRUE),] 
som_shared_t50 <- som_shared[c(1:50),]

# graph all important features with gibbs features highlighted
p1 <- ggplot(som_shared_t50, aes(x = reorder(Taxon, -avg_imp), y = avg_imp)) +
  geom_bar(stat = "identity", width = .5) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "SOM Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_TAX_SOM.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_TAX_SOM.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

# Water capacity
```{r}
# make list of file names
filenames = list.files(pattern="\\.csv$",
                  path = "machine_learning/16S_TAX/WATERCAP_model_results",
                  full.names = T)
ldf <- lapply(filenames, read.csv)

# remove stats file from ldf
ldf <- ldf[-1]

# format column names
colnames <- c("Taxon","importance")
ldf <- lapply(ldf, setNames, colnames)

# filter out negative importances - neg importances reduce predictive value
ldf <- lapply(ldf, function(x) filter(x, importance > 0))

# get list of features overlapping between all 25 dfs
watercap_shared <- ldf %>% reduce(inner_join, by = "Taxon")

# calculate average importance of all shared features
watercap_shared$avg_imp <- rowMeans(watercap_shared[,2:26])
watercap_shared <- watercap_shared[,c(1,27)]
watercap_shared <- data.frame(watercap_shared)
watercap_shared$indicator <- "WATERCAP"

# there are too many important features to graph
# sort by avg_imp and filter down to the top 50
watercap_shared <- watercap_shared[order(watercap_shared$avg_imp, decreasing = TRUE),] 
watercap_shared_t50 <- watercap_shared[c(1:50),]

# graph all important features with gibbs features highlighted
p1 <- ggplot(watercap_shared_t50, aes(x = reorder(Taxon, -avg_imp), y = avg_imp)) +
  geom_bar(stat = "identity", width = .5) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Water Capacity Important Features",
       y = "Average Importance Across 25 Models")
p1
ggsave("figures/feat_importance_TAX_WATERCAP.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_TAX_WATERCAP.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")
```

### Combine shared features for all indicators
```{r}
# make sure to add dist and shmi when they're done
list_tax_dfs <- list(ace_shared, activeC_shared, aggstab_shared, cash_shared,
                    resp_shared, rich_shared, root_shared, 
                    semwise_shared, som_shared, watercap_shared)
tax_shared <- list_tax_dfs %>% reduce(inner_join, by = "Taxon")
# the only important feature shared by all 25 models in all indicators is climate
# do a full join and count the number of indicators each feature is important in

tax_all <- list_tax_dfs %>% reduce(full_join, by = "Taxon")
# make sure to add 23 and 25 to the next line when dist and shmi are done
tax_all <- tax_all[,c(1,3,5,7,9,11,13,15,17,19,21)]
# add dist and shmi to list of colnames when done
colnames_list <- c("feature","ACE","ACTIVEC","AGGSTAB","CASH","RESP",
                   "RICH","ROOT","SEMWISE","SOM","WATERCAP")
colnames(tax_all) <- colnames_list
# change 11 to 13 when dist and shmi are done
tax_all$num_indic_imp <- rowSums(!is.na(tax_all[,2:11]))

# filter taxs_all down to features that were important in 6 or more indicators
tax_all_filt <- filter(tax_all, num_indic_imp > 5)

p1 <- ggplot(tax_all_filt, aes(x = reorder(feature, -num_indic_imp), y = num_indic_imp)) +
  geom_bar(stat = "identity", width = .5) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Features Important in Six or More Indicators",
       y = "Number of Indicators Feature is Important In")
p1
ggsave("figures/feat_importance_tax_all.pdf", unit = "in", width = 10, height = 6, dpi = 300, device = "pdf")
ggsave("figures/feat_importance_tax_all.tiff", unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")


```




