---
title: "Random Forest, 16S taxonomic data"
author: "Heather Deel"
date: "2023-09-12"
output: html_document
---

### Setup and packages
```{r setup, include=FALSE}
library(tidymodels)
library(tidyverse)
library(workflows)
library(tune)
library(metagMisc)
library(ranger)
library(randomForest)
library(janitor)
```

### Load and format data
# Performed in scinet


### need to read in metadata, get metadata into same df as OTU table, qPCR correct all of the counts in the OTU table?
```{r}
tax <- read.delim("/project/soil_micro_lab/micro_indicators/machine_learning/16S_TAX/All.tx.dada.txt")

# metadata
data.pred.SHMI <- readRDS("/project/soil_micro_lab/micro_indicators/machine_learning/data.pred.SHMI.RDS")

# read in metadata that includes sampleIDs to merge with data.pred.SHMI
data.sampleID <- read.delim('/project/soil_micro_lab/micro_indicators/machine_learning/SHAI.Meta.22March2023.q2.reduced.txt', sep = '\t')

# merge metadata files
data.merged <- merge(data.pred.SHMI, data.sampleID, by = "PLFA_ID", all.x = TRUE)

# move the sample ID column to the front
data.merged <- data.merged %>% 
  relocate(SampleID)

# transpose tax
tax_t <- t(tax)

# make OTUID row the column names 
tax_t <- tax_t %>% 
  row_to_names(row_number = 1)

# get rownames to column for merging
tax_t <- as.data.frame(tax_t)
tax_t <- rownames_to_column(tax_t, "SampleID")

# get qPCR data into tax data

######### need to get the correct qPCR column, not the scaled one
qPCR_data <- data.merged[,c(1,99)]
tax2 <- merge(tax_t, qPCR_data, by = "SampleID")



##### need to get relative abundance of everything

# multiply everything by qPCR column
tax2 <- column_to_rownames(tax2, var = "SampleID")
tax2 <- tax2 %>% 
  relocate(qPCR)
tax3 <- mutate_all(tax2, function(x) as.numeric(as.character(x)))
  
tax_total <- tax3 %>% 
  mutate(across(everything(), ~ .x*qPCR))

# get rest of metadata into tax data


# save object for future subsetting


```

