---
title: "Machine Learning Graphing"
author: "Heather Deel"
date: "2023-09-18"
output: html_document
---

### Libraries
```{r}
library(ggplot2)
library(readxl)
library(ggpubr)
library(paletteer)
library(tidyverse)
```

### Comparison of taxonomic and EC relative abundance and total data
```{r}
# compare the r^2 distributions of 1-25 models
# just clean up the same figure Dan made

```

### Boxplot of R^2 values for each indicator
```{r}
ml_stats <- read.csv("machine_learning/16S_EC/All_EC_RA_total_corr_stats.csv")
ml_stats_RA <- ml_stats[ml_stats$RA_total == "RA",]
ml_stats_total <- ml_stats[ml_stats$RA_total == "total",]


stat.test.RA <- compare_means(r2_val ~ myVar,
                           data = ml_stats_RA,
                           method = 'wilcox.test',
                           p.adj = 'fdr')
stat.test.total <- compare_means(r2_val ~ myVar,
                           data = ml_stats_total,
                           method = 'wilcox.test',
                           p.adj = 'fdr')
stat.test.RA$Comparison <- paste0(stat.test.RA$group1, " - ", stat.test.RA$group2)
stat.test.total$Comparison <- paste0(stat.test.total$group1, " - ", stat.test.total$group2)
groups.RA <- rcompanion::cldList(p.adj ~ Comparison,
                              data = stat.test.RA,
                              threshold = 0.05)
groups.total <- rcompanion::cldList(p.adj ~ Comparison,
                              data = stat.test.total,
                              threshold = 0.05)
  
groups.RA$y <- 1.2
groups.total$y <- 1.2

p1 <- ggplot(ml_stats_RA, aes(x=myVar, y=r2_val)) + 
  geom_boxplot(fill='grey') + 
  labs(y='R^2 Values', x='Indicator', title = "EC Model Prediction Accuracy, Relative Abundance") + 
  theme_bw() + 
  ylim(0,1.2) +
  theme(axis.text.x=element_text(angle=45, hjust=1)) +
  geom_text(inherit.aes=F, data=groups.RA, aes(x=Group, y=y, label=Letter)) # add significances
p1

ggsave("figures/ml_ec_r2_RA.pdf", unit = "in", width = 8, height = 6, dpi = 300, device = "pdf")
ggsave("figures/ml_ec_r2_RA.tiff", unit = "in", width = 8, height = 6, dpi = 300, device = "tiff")

p2 <- ggplot(ml_stats_total, aes(x=myVar, y=r2_val)) + 
  geom_boxplot(fill='grey') + 
  labs(y='R^2 Values', x='Indicator', title = "EC Model Prediction Accuracy, Total Abundance") + 
  theme_bw() + 
  ylim(0,1.2) +
  theme(axis.text.x=element_text(angle=45, hjust=1)) +
  geom_text(inherit.aes=F, data=groups.total, aes(x=Group, y=y, label=Letter)) # add significances
p2

ggsave("figures/ml_ec_r2_total.pdf", unit = "in", width = 8, height = 6, dpi = 300, device = "pdf")
ggsave("figures/ml_ec_r2_total.tiff", unit = "in", width = 8, height = 6, dpi = 300, device = "tiff")
```

### Feature importance distributions
```{r}
gibbs <- read.csv('picrust2_files/GIBBs.EC.numbers.csv')
gibbs$EC <- gsub(":","_", gibbs$EC)
gibbs$EC <- gsub("\\.","_", gibbs$EC)

myVars <- c('ace', 'SOM', 'activeC', 'resp', 'agg_stab', 'water_cap', 'ph', 'p', 'k', 'mg', 'fe', 'mn', 'zn')

### ace
myVar <- 'ace'

df <- read.csv(paste0("machine_learning/16S_EC/", myVar, "_model_results_RA_corr/", myVar, "_RA_corr_varimp.csv"), header=FALSE)
names(df) <- c('Predictor', 'VIP', 'Run')

gDF <- df %>%
  left_join(gibbs, by=c("Predictor"="EC")) %>% 
  mutate(Short=fct_reorder(Short, VIP, .fun=mean, .desc=TRUE)) # sort levels by mean VIP

gDF <- gDF %>% group_by(Predictor) %>%
  mutate(Var = mean(VIP)) %>%
  filter(Var > 0.01) %>% select(-Var) # filter out poor indicators

ace_varimp_list <- unique(gDF$Predictor)
ace_varimp <- data.frame(ace_varimp_list)
ace_varimp$indicator <- "ace"
colnames(ace_varimp)[1] <- "Predictor"

ace_varimp_list <- "ClimateZ"
# just testing to see if it even works when indicators are important in more than one model. No it does not.

ace_imps <- data.frame()
for (predictor in ace_varimp_list) {
  gDF_ace <- gDF %>% 
    filter(Predictor == predictor) }
  if (length(gDF_ace$Predictor == 1)) {
    gDF_ace$VIP_avg <- gDF_ace$VIP
    ace_imps <- append(ace_imps, list(gDF_ace$Predictor, gDF_ace$VIP_avg))
    ace_imps <- data.frame(ace_imps)
  } else {
    gDF_ace$VIP_avg <- colMeans(gDF_ace$VIP)
    ace_imps <- append(ace_imps, list(gDF_ace$Predictor, gDF_ace$VIP_avg))
    ace_imps <- data.frame(ace_imps)
  }

# calculate average importance of all shared features
ace_shared$avg_imp <- rowMeans(ace_shared[,2:26])
ace_shared <- ace_shared[,c(1,27)]
ace_shared <- data.frame(ace_shared)
colnames(ace_shared)[1] <- "feature"
ace_shared$indicator <- "ACE"

ace_ECs <- list(ace_varimp$Predictor)












colors <- paletteer_d(`"ggsci::category20_d3"`)

p <- ggplot(gDF, aes(x=Predictor, y=VIP, fill=Category)) +
  scale_fill_manual(values=colors, na.value="white") +
  geom_boxplot() + 
  theme_bw() +
  theme(axis.text.x=element_text(angle=90)) +
  labs(x="", y="Variable Importance", title = myVar)
p
ggsave(paste0("figures/", myVar, "_varimp.tiff"), unit = "in", width = 8, height = 6, dpi = 300, device = "tiff")

### SOM
myVar <- 'SOM'

df <- read.csv(paste0("machine_learning/16S_EC/", myVar, "_model_results_RA_corr/", myVar, "_RA_corr_varimp.csv"), header=FALSE)
names(df) <- c('Predictor', 'VIP', 'Run')

gDF <- df %>%
  left_join(gibbs, by=c("Predictor"="EC")) %>% 
  mutate(Short=fct_reorder(Short, VIP, .fun=mean, .desc=TRUE)) # sort levels by mean VIP

gDF <- gDF %>% group_by(Predictor) %>%
  mutate(Var = mean(VIP)) %>%
  filter(Var > 0.01) %>% select(-Var) # filter out poor indicators


som_varimp_list <- unique(gDF$Predictor)
som_varimp <- data.frame(som_varimp_list)
som_varimp$indicator <- "SOM"
colnames(som_varimp)[1] <- "Predictor"

colors <- paletteer_d(`"ggsci::category20_d3"`)

p <- ggplot(gDF, aes(x=Predictor, y=VIP, fill=Category)) +
  scale_fill_manual(values=colors, na.value="white") +
  geom_boxplot() + 
  theme_bw() +
  theme(axis.text.x=element_text(angle=90)) +
  labs(x="", y="Variable Importance", title = myVar)
p
ggsave(paste0("figures/", myVar, "_varimp.tiff"), unit = "in", width = 8, height = 6, dpi = 300, device = "tiff")

### activeC
myVar <- 'activeC'

df <- read.csv(paste0("machine_learning/16S_EC/", myVar, "_model_results_RA_corr/", myVar, "_RA_corr_varimp.csv"), header=FALSE)
names(df) <- c('Predictor', 'VIP', 'Run')

gDF <- df %>%
  left_join(gibbs, by=c("Predictor"="EC")) %>% 
  mutate(Short=fct_reorder(Short, VIP, .fun=mean, .desc=TRUE)) # sort levels by mean VIP

gDF <- gDF %>% group_by(Predictor) %>%
  mutate(Var = mean(VIP)) %>%
  filter(Var > 0.01) %>% select(-Var) # filter out poor indicators


activeC_varimp_list <- unique(gDF$Predictor)
activeC_varimp <- data.frame(activeC_varimp_list)
activeC_varimp$indicator <- "activeC"
colnames(activeC_varimp)[1] <- "Predictor"

colors <- paletteer_d(`"ggsci::category20_d3"`)

p <- ggplot(gDF, aes(x=Predictor, y=VIP, fill=Category)) +
  scale_fill_manual(values=colors, na.value="white") +
  geom_boxplot() + 
  theme_bw() +
  theme(axis.text.x=element_text(angle=90)) +
  labs(x="", y="Variable Importance", title = myVar)
p
ggsave(paste0("figures/", myVar, "_varimp.tiff"), unit = "in", width = 8, height = 6, dpi = 300, device = "tiff")

### resp
myVar <- 'resp'

df <- read.csv(paste0("machine_learning/16S_EC/", myVar, "_model_results_RA_corr/", myVar, "_RA_corr_varimp.csv"), header=FALSE)
names(df) <- c('Predictor', 'VIP', 'Run')

gDF <- df %>%
  left_join(gibbs, by=c("Predictor"="EC")) %>% 
  mutate(Short=fct_reorder(Short, VIP, .fun=mean, .desc=TRUE)) # sort levels by mean VIP

gDF <- gDF %>% group_by(Predictor) %>%
  mutate(Var = mean(VIP)) %>%
  filter(Var > 0.01) %>% select(-Var) # filter out poor indicators


resp_varimp_list <- unique(gDF$Predictor)
resp_varimp <- data.frame(resp_varimp_list)
resp_varimp$indicator <- "resp"
colnames(resp_varimp)[1] <- "Predictor"

colors <- paletteer_d(`"ggsci::category20_d3"`)

p <- ggplot(gDF, aes(x=Predictor, y=VIP, fill=Category)) +
  scale_fill_manual(values=colors, na.value="white") +
  geom_boxplot() + 
  theme_bw() +
  theme(axis.text.x=element_text(angle=90)) +
  labs(x="", y="Variable Importance", title = myVar)
p
ggsave(paste0("figures/", myVar, "_varimp.tiff"), unit = "in", width = 8, height = 6, dpi = 300, device = "tiff")

### agg_stab
myVar <- 'agg_stab'

df <- read.csv(paste0("machine_learning/16S_EC/", myVar, "_model_results_RA_corr/", myVar, "_RA_corr_varimp.csv"), header=FALSE)
names(df) <- c('Predictor', 'VIP', 'Run')

gDF <- df %>%
  left_join(gibbs, by=c("Predictor"="EC")) %>% 
  mutate(Short=fct_reorder(Short, VIP, .fun=mean, .desc=TRUE)) # sort levels by mean VIP

gDF <- gDF %>% group_by(Predictor) %>%
  mutate(Var = mean(VIP)) %>%
  filter(Var > 0.01) %>% select(-Var) # filter out poor indicators


agg_stab_varimp_list <- unique(gDF$Predictor)
agg_stab_varimp <- data.frame(agg_stab_varimp_list)
agg_stab_varimp$indicator <- "agg_stab"
colnames(agg_stab_varimp)[1] <- "Predictor"

colors <- paletteer_d(`"ggsci::category20_d3"`)

p <- ggplot(gDF, aes(x=Predictor, y=VIP, fill=Category)) +
  scale_fill_manual(values=colors, na.value="white") +
  geom_boxplot() + 
  theme_bw() +
  theme(axis.text.x=element_text(angle=90)) +
  labs(x="", y="Variable Importance", title = myVar)
p
ggsave(paste0("figures/", myVar, "_varimp.tiff"), unit = "in", width = 8, height = 6, dpi = 300, device = "tiff")

### water_cap
myVar <- 'water_cap'

df <- read.csv(paste0("machine_learning/16S_EC/", myVar, "_model_results_RA_corr/", myVar, "_RA_corr_varimp.csv"), header=FALSE)
names(df) <- c('Predictor', 'VIP', 'Run')

gDF <- df %>%
  left_join(gibbs, by=c("Predictor"="EC")) %>% 
  mutate(Short=fct_reorder(Short, VIP, .fun=mean, .desc=TRUE)) # sort levels by mean VIP

gDF <- gDF %>% group_by(Predictor) %>%
  mutate(Var = mean(VIP)) %>%
  filter(Var > 0.01) %>% select(-Var) # filter out poor indicators


water_cap_varimp_list <- unique(gDF$Predictor)
water_cap_varimp <- data.frame(water_cap_varimp_list)
water_cap_varimp$indicator <- "water_cap"
colnames(water_cap_varimp)[1] <- "Predictor"

colors <- paletteer_d(`"ggsci::category20_d3"`)

p <- ggplot(gDF, aes(x=Predictor, y=VIP, fill=Category)) +
  scale_fill_manual(values=colors, na.value="white") +
  geom_boxplot() + 
  theme_bw() +
  theme(axis.text.x=element_text(angle=90)) +
  labs(x="", y="Variable Importance", title = myVar)
p
ggsave(paste0("figures/", myVar, "_varimp.tiff"), unit = "in", width = 8, height = 6, dpi = 300, device = "tiff")

### ph
myVar <- 'ph'

df <- read.csv(paste0("machine_learning/16S_EC/", myVar, "_model_results_RA_corr/", myVar, "_RA_corr_varimp.csv"), header=FALSE)
names(df) <- c('Predictor', 'VIP', 'Run')

gDF <- df %>%
  left_join(gibbs, by=c("Predictor"="EC")) %>% 
  mutate(Short=fct_reorder(Short, VIP, .fun=mean, .desc=TRUE)) # sort levels by mean VIP

gDF <- gDF %>% group_by(Predictor) %>%
  mutate(Var = mean(VIP)) %>%
  filter(Var > 0.01) %>% select(-Var) # filter out poor indicators


ph_varimp_list <- unique(gDF$Predictor)
ph_varimp <- data.frame(ph_varimp_list)
ph_varimp$indicator <- "ph"
colnames(ph_varimp)[1] <- "Predictor"

colors <- paletteer_d(`"ggsci::category20_d3"`)

p <- ggplot(gDF, aes(x=Predictor, y=VIP, fill=Category)) +
  scale_fill_manual(values=colors, na.value="white") +
  geom_boxplot() + 
  theme_bw() +
  theme(axis.text.x=element_text(angle=90)) +
  labs(x="", y="Variable Importance", title = myVar)
p
ggsave(paste0("figures/", myVar, "_varimp.tiff"), unit = "in", width = 8, height = 6, dpi = 300, device = "tiff")

### p
myVar <- 'p'

df <- read.csv(paste0("machine_learning/16S_EC/", myVar, "_model_results_RA_corr/", myVar, "_RA_corr_varimp.csv"), header=FALSE)
names(df) <- c('Predictor', 'VIP', 'Run')

gDF <- df %>%
  left_join(gibbs, by=c("Predictor"="EC")) %>% 
  mutate(Short=fct_reorder(Short, VIP, .fun=mean, .desc=TRUE)) # sort levels by mean VIP

gDF <- gDF %>% group_by(Predictor) %>%
  mutate(Var = mean(VIP)) %>%
  filter(Var > 0.01) %>% select(-Var) # filter out poor indicators

p_varimp_list <- unique(gDF$Predictor)
p_varimp <- data.frame(p_varimp_list)
p_varimp$indicator <- "p"
colnames(p_varimp)[1] <- "Predictor"

colors <- paletteer_d(`"ggsci::category20_d3"`)

p <- ggplot(gDF, aes(x=Predictor, y=VIP, fill=Category)) +
  scale_fill_manual(values=colors, na.value="white") +
  geom_boxplot() + 
  theme_bw() +
  theme(axis.text.x=element_text(angle=90)) +
  labs(x="", y="Variable Importance", title = myVar)
p
ggsave(paste0("figures/", myVar, "_varimp.tiff"), unit = "in", width = 8, height = 6, dpi = 300, device = "tiff")

### k
myVar <- 'k'

df <- read.csv(paste0("machine_learning/16S_EC/", myVar, "_model_results_RA_corr/", myVar, "_RA_corr_varimp.csv"), header=FALSE)
names(df) <- c('Predictor', 'VIP', 'Run')

gDF <- df %>%
  left_join(gibbs, by=c("Predictor"="EC")) %>% 
  mutate(Short=fct_reorder(Short, VIP, .fun=mean, .desc=TRUE)) # sort levels by mean VIP

gDF <- gDF %>% group_by(Predictor) %>%
  mutate(Var = mean(VIP)) %>%
  filter(Var > 0.01) %>% select(-Var) # filter out poor indicators

k_varimp_list <- unique(gDF$Predictor)
k_varimp <- data.frame(k_varimp_list)
k_varimp$indicator <- "k"
colnames(k_varimp)[1] <- "Predictor"

colors <- paletteer_d(`"ggsci::category20_d3"`)

p <- ggplot(gDF, aes(x=Predictor, y=VIP, fill=Category)) +
  scale_fill_manual(values=colors, na.value="white") +
  geom_boxplot() + 
  theme_bw() +
  theme(axis.text.x=element_text(angle=90)) +
  labs(x="", y="Variable Importance", title = myVar)
p
ggsave(paste0("figures/", myVar, "_varimp.tiff"), unit = "in", width = 10, height = 6, dpi = 300, device = "tiff")

### mg
myVar <- 'mg'

df <- read.csv(paste0("machine_learning/16S_EC/", myVar, "_model_results_RA_corr/", myVar, "_RA_corr_varimp.csv"), header=FALSE)
names(df) <- c('Predictor', 'VIP', 'Run')

gDF <- df %>%
  left_join(gibbs, by=c("Predictor"="EC")) %>% 
  mutate(Short=fct_reorder(Short, VIP, .fun=mean, .desc=TRUE)) # sort levels by mean VIP

gDF <- gDF %>% group_by(Predictor) %>%
  mutate(Var = mean(VIP)) %>%
  filter(Var > 0.01) %>% select(-Var) # filter out poor indicators

mg_varimp_list <- unique(gDF$Predictor)
mg_varimp <- data.frame(mg_varimp_list)
mg_varimp$indicator <- "mg"
colnames(mg_varimp)[1] <- "Predictor"

colors <- paletteer_d(`"ggsci::category20_d3"`)

p <- ggplot(gDF, aes(x=Predictor, y=VIP, fill=Category)) +
  scale_fill_manual(values=colors, na.value="white") +
  geom_boxplot() + 
  theme_bw() +
  theme(axis.text.x=element_text(angle=90)) +
  labs(x="", y="Variable Importance", title = myVar)
p
ggsave(paste0("figures/", myVar, "_varimp.tiff"), unit = "in", width = 8, height = 6, dpi = 300, device = "tiff")

### fe
myVar <- 'fe'

df <- read.csv(paste0("machine_learning/16S_EC/", myVar, "_model_results_RA_corr/", myVar, "_RA_corr_varimp.csv"), header=FALSE)
names(df) <- c('Predictor', 'VIP', 'Run')

gDF <- df %>%
  left_join(gibbs, by=c("Predictor"="EC")) %>% 
  mutate(Short=fct_reorder(Short, VIP, .fun=mean, .desc=TRUE)) # sort levels by mean VIP

gDF <- gDF %>% group_by(Predictor) %>%
  mutate(Var = mean(VIP)) %>%
  filter(Var > 0.01) %>% select(-Var) # filter out poor indicators

fe_varimp_list <- unique(gDF$Predictor)
fe_varimp <- data.frame(fe_varimp_list)
fe_varimp$indicator <- "fe"
colnames(fe_varimp)[1] <- "Predictor"

colors <- paletteer_d(`"ggsci::category20_d3"`)

p <- ggplot(gDF, aes(x=Predictor, y=VIP, fill=Category)) +
  scale_fill_manual(values=colors, na.value="white") +
  geom_boxplot() + 
  theme_bw() +
  theme(axis.text.x=element_text(angle=90)) +
  labs(x="", y="Variable Importance", title = myVar)
p
ggsave(paste0("figures/", myVar, "_varimp.tiff"), unit = "in", width = 8, height = 6, dpi = 300, device = "tiff")

### mn
myVar <- 'mn'

df <- read.csv(paste0("machine_learning/16S_EC/", myVar, "_model_results_RA_corr/", myVar, "_RA_corr_varimp.csv"), header=FALSE)
names(df) <- c('Predictor', 'VIP', 'Run')

gDF <- df %>%
  left_join(gibbs, by=c("Predictor"="EC")) %>% 
  mutate(Short=fct_reorder(Short, VIP, .fun=mean, .desc=TRUE)) # sort levels by mean VIP

gDF <- gDF %>% group_by(Predictor) %>%
  mutate(Var = mean(VIP)) %>%
  filter(Var > 0.01) %>% select(-Var) # filter out poor indicators

mn_varimp_list <- unique(gDF$Predictor)
mn_varimp <- data.frame(mn_varimp_list)
mn_varimp$indicator <- "mn"
colnames(mn_varimp)[1] <- "Predictor"

colors <- paletteer_d(`"ggsci::category20_d3"`)

p <- ggplot(gDF, aes(x=Predictor, y=VIP, fill=Category)) +
  scale_fill_manual(values=colors, na.value="white") +
  geom_boxplot() + 
  theme_bw() +
  theme(axis.text.x=element_text(angle=90)) +
  labs(x="", y="Variable Importance", title = myVar)
p
ggsave(paste0("figures/", myVar, "_varimp.tiff"), unit = "in", width = 8, height = 6, dpi = 300, device = "tiff")

### zn
myVar <- 'zn'

df <- read.csv(paste0("machine_learning/16S_EC/", myVar, "_model_results_RA_corr/", myVar, "_RA_corr_varimp.csv"), header=FALSE)
names(df) <- c('Predictor', 'VIP', 'Run')

gDF <- df %>%
  left_join(gibbs, by=c("Predictor"="EC")) %>% 
  mutate(Short=fct_reorder(Short, VIP, .fun=mean, .desc=TRUE)) # sort levels by mean VIP

gDF <- gDF %>% group_by(Predictor) %>%
  mutate(Var = mean(VIP)) %>%
  filter(Var > 0.01) %>% select(-Var) # filter out poor indicators

zn_varimp_list <- unique(gDF$Predictor)
zn_varimp <- data.frame(zn_varimp_list)
zn_varimp$indicator <- "zn"
colnames(zn_varimp)[1] <- "Predictor"

colors <- paletteer_d(`"ggsci::category20_d3"`)

p <- ggplot(gDF, aes(x=Predictor, y=VIP, fill=Category)) +
  scale_fill_manual(values=colors, na.value="white") +
  geom_boxplot() + 
  theme_bw() +
  theme(axis.text.x=element_text(angle=90)) +
  labs(x="", y="Variable Importance", title = myVar)
p
ggsave(paste0("figures/", myVar, "_varimp.tiff"), unit = "in", width = 8, height = 6, dpi = 300, device = "tiff")
```

### Make varimp list of all indicators
```{r}
# importances not attached yet. need to figure out how to do that. started trying to with ace
all_varimp <- rbind(ace_varimp, activeC_varimp, agg_stab_varimp, fe_varimp, 
                    k_varimp, mg_varimp, mn_varimp, p_varimp, ph_varimp, 
                    resp_varimp, som_varimp, water_cap_varimp, zn_varimp)
write.csv(all_varimp, file = "machine_learning/16S_EC/all_varimps_list.csv", row.names = FALSE)
```


### Partial dependence plots
```{r}
# show response of important features to each indicator
# just do this on a final model
```

