---
title: "Machine Learning Graphing"
author: "Heather Deel"
date: "2023-09-18"
output: html_document
---

### Libraries
```{r}
library(ggplot2)
library(readxl)
library(ggpubr)
```

### Boxplot of 16S_EC R^2 values
```{r}
ml_16S_stats <- read_xlsx("machine_learning/16S_EC/ALL_ec_16S_stats.xlsx")

stat.test <- compare_means(r2_value_pred_vs_obs ~ prediction,
                           data = ml_16S_stats,
                           method = 'wilcox.test',
                           p.adj = 'fdr')
stat.test$Comparison <- paste0(stat.test$group1, " - ", stat.test$group2)
groups <- rcompanion::cldList(p.adj ~ Comparison,
                              data = stat.test,
                              threshold = 0.05)
  
groups$y <- 0.9

# reordering from highest to lowest r^2 values
ml_16S_stats$prediction <- factor(ml_16S_stats$prediction, levels = c('ACE','ACTIVEC',
                                                              'SHMI','SOM','DIST',
                                                              'CASH','RESP','ROOT',
                                                              'AGGSTAB','WATERCAP',
                                                              'SEMWISE','RICH'))

p1 <- ggplot(ml_16S_stats, aes(x=prediction, y=r2_value_pred_vs_obs)) + 
  geom_boxplot(fill='grey') + 
  labs(y='R^2 Values', x='Prediction Type') + 
  theme_bw() + 
  theme(axis.text.x=element_text(angle=45, hjust=1)) +
  geom_text(inherit.aes=F, data=groups, aes(x=Group, y=y, label=Letter))
p1

ggsave("machine_learning/16S_EC/16S_EC_ml_r2.tiff", unit = "in", width = 6, height = 6, dpi = 300, device = "tiff")
```

### Boxplots of 18S_EC R^2 values
# currently only have a few prediction types - others currently running
```{r}
ml_18S_stats <- read_xlsx("machine_learning/18S_EC/ALL_ec_18S_stats.xlsx")

stat.test <- compare_means(r2_value_pred_vs_obs ~ prediction,
                           data = ml_18S_stats,
                           method = 'wilcox.test',
                           p.adj = 'fdr')
stat.test$Comparison <- paste0(stat.test$group1, " - ", stat.test$group2)
groups <- rcompanion::cldList(p.adj ~ Comparison,
                              data = stat.test,
                              threshold = 0.05)
  
groups$y <- 0.9

# reordering from highest to lowest r^2 values
#ml_18S_stats$prediction <- factor(ml_18S_stats$prediction, levels = c('ACE','ACTIVEC',
#                                                              'SHMI','SOM','DIST',
#                                                              'CASH','RESP','ROOT',
#                                                              'AGGSTAB','WATERCAP',
#                                                              'SEMWISE','RICH'))

p1 <- ggplot(ml_18S_stats, aes(x=prediction, y=r2_value_pred_vs_obs)) + 
  geom_boxplot(fill='grey') + 
  labs(y='R^2 Values', x='Prediction Type') + 
  theme_bw() + 
  theme(axis.text.x=element_text(angle=45, hjust=1)) +
  geom_text(inherit.aes=F, data=groups, aes(x=Group, y=y, label=Letter))
p1

#ggsave("machine_learning/18S_EC/18S_EC_ml_r2.tiff", unit = "in", width = 6, height = 6, dpi = 300, device = "tiff")
```
