---
title: "Machine Learning Graphing"
author: "Heather Deel"
date: "2023-09-18"
output: html_document
---

### Libraries
```{r}
library(ggplot2)
library(readxl)
library(ggpubr)
```

### Boxplot of EC R^2 values
```{r}
ml_stats <- read_xlsx("machine_learning/16S_EC/ml_EC_stats_all.xlsx")

stat.test <- compare_means(r2_val ~ model_type,
                           data = ml_stats,
                           method = 'wilcox.test',
                           p.adj = 'fdr')
stat.test$Comparison <- paste0(stat.test$group1, " - ", stat.test$group2)
groups <- rcompanion::cldList(p.adj ~ Comparison,
                              data = stat.test,
                              threshold = 0.05)
  
groups$y <- 0.9

# reordering from highest to lowest r^2 values
ml_stats$model_type <- factor(ml_stats$model_type, levels = c('ACE','SOM','SHMI',
                                                              'ACTIVEC','RESP','DIST',
                                                              'WATERCAP','ROOT','AGGSTAB',
                                                              'CASH','SEMWISE','RICH'))

p1 <- ggplot(ml_stats, aes(x=model_type, y=r2_val)) + 
  geom_boxplot(fill='grey') + 
  labs(y='R^2 Values', x='Prediction Type', title = "EC Model Prediction Accuracy") + 
  theme_bw() + 
  ylim(0,0.90) +
  theme(axis.text.x=element_text(angle=45, hjust=1)) +
  geom_text(inherit.aes=F, data=groups, aes(x=Group, y=y, label=Letter)) # add significances
p1

ggsave("figures/ml_ec_r2.pdf", unit = "in", width = 8, height = 6, dpi = 300, device = "pdf")
ggsave("figures/ml_ec_r2.tiff", unit = "in", width = 8, height = 6, dpi = 300, device = "tiff")
```

### Boxplot of taxonomic R^2 values
```{r}
ml_stats <- read_xlsx("machine_learning/16S_TAX/ml_tax_stats_all.xlsx")

stat.test <- compare_means(r2_val ~ model_type,
                           data = ml_stats,
                           method = 'wilcox.test',
                           p.adj = 'fdr')
stat.test$Comparison <- paste0(stat.test$group1, " - ", stat.test$group2)
groups <- rcompanion::cldList(p.adj ~ Comparison,
                              data = stat.test,
                              threshold = 0.05)
  
groups$y <- 0.9

# reordering from highest to lowest r^2 values
ml_stats$model_type <- factor(ml_stats$model_type, levels = c('ACE','SOM',
                                                              'ACTIVEC','WATERCAP',
                                                              'AGGSTAB','RESP','ROOT',
                                                              'CASH','RICH','SEMWISE'))

p2 <- ggplot(ml_stats, aes(x=model_type, y=r2_val)) + 
  geom_boxplot(fill='grey') + 
  labs(y='R^2 Values', x='Prediction Type', title = "Taxonomic Model Prediction Accuracy") + 
  theme_bw() + 
  ylim(0,0.90) +
  theme(axis.text.x=element_text(angle=45, hjust=1)) +
  geom_text(inherit.aes=F, data=groups, aes(x=Group, y=y, label=Letter)) # add significances
p2

ggsave("figures/ml_tax_r2.pdf", unit = "in", width = 8, height = 6, dpi = 300, device = "pdf")
ggsave("figures/ml_tax_r2.tiff", unit = "in", width = 8, height = 6, dpi = 300, device = "tiff")
```

### Merge EC and tax graphs to compare
```{r}
ec_tax_r2 <- ggarrange(p1, p2,
                    labels = c("A", "B"),
                    ncol = 2, nrow = 1)
ec_tax_r2

ggsave("figures/ml_ec_tax_r2.pdf", unit = "in", width = 8, height = 4, dpi = 300, device = "pdf")
ggsave("figures/ml_ec_tax_r2.tiff", unit = "in", width = 8, height = 4, dpi = 300, device = "tiff")
```



